### ISSUE TITLE
Translation on gun/ammo

### ISSUE THREAD

**Issue by Aleweadan** [ImagicTheCat/vRP-basic-mission#7]
Hello, we can't have translation for gun and ammo if i put this code :
`  ["mission.delivery.gun"] = {
    chance = 30,
    positions = gunshop_positions,
    items = {
      ["wbody|WEAPON_PISTOL"] = {1,5,100},
      ["wammo|WEAPON_PISTOL"] = {1,60,10},
	  ["wbody|WEAPON_PUMPSHOTGUN"] = {1,3,1500},
      ["wammo|WEAPON_PUMPSHOTGUN"] = {1,40,25},
	  ["wbody|WEAPON_SMG"] = {1,2,250},
      ["wammo|WEAPON_SMG"] = {1,30,30}
    }
  }
}`
In game i will have only english words in missions chart

**Comment by ImagicTheCat** [comment]
True, there is no way currently to get the weapon name per identifier server-side. 
Nothing stop you from modifying the wammo and wbody definition, since it is in config files.

**Comment by Aleweadan** [comment]
In cfg/item/required.lua ? Can you give me an example please ? I don't understand how to name it.

**Comment by ImagicTheCat** [comment]
I can't give examples because there isn't really a solution about this, try to ask help on the forum or on the discord if someone did something about it. Let the issue open, I could make something using the lang system one day. 

edit: I will close it and open a mirror because it has nothing to do with basic missions.
